openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: user
    description: Operations about user
  - name: vehicle
    description: Operations about vehicle
  - name: policy
    description: Operations about policy
  - name: part
    description: Operations about part
  - name: peritage
    description: Operations about peritage
paths:

  /users:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      tags:
        - user
      summary: Get user by ID
      description: ''
      operationId: getUserById


      parameters:
        - in: path
          name: id
          description: 'The id that needs to be fetched. '
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Delete user by id
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid id supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation

  /polizyes:
    get:
      tags:
        - policy
      summary: Find policy by dni
      description: Returns a single policy
      operationId: getPolicyByDni
      parameters:
        - name: tomadorDni
          in: query
          description: filter tomadorDni
          schema:
            type: string
        - name: benefitDni
          in: query
          description: filter benefitDni
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '400':
          description: Invalid DNI supplied
        '404':
          description: Policy not found
    post:
      tags:
        - policy
      summary: create a policy for a user
      description: create a new policy in the bbdd
      operationId: createPolicy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
      responses:
        '200':
          description: successful operation - poliza creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '405':
          description: Invalid input

  /polizyes/types:
    get:
      tags:
        - policy
      summary: Finds types of police
      description: return types
      operationId: findTypesOfPolicy
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PolicyTypes'

  /polizyes/{idPolicy}/parts/{idPart}/peritage:
    post:
      tags:
        - part
      summary: execute peritage action to part
      description: execute peritage action to part
      operationId: doPeritageAction
      parameters:
        - name: idPolicy
          in: path
          description: idPoliza of part that needs to be fetched
          required: true
          schema:
            type: string
        - name: idPart
          in: path
          description: idPart that needs to be fetched
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peritage'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peritage'

  /vehicles:
    get:
      tags:
        - vehicle
      summary: Find vehicle by dniPropietario
      description: returns vehicles by dniPropietario
      operationId: getVehicleByDni
      parameters:
        - name: dniPropietario
          in: query
          description: dniPropietario of vehicles that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Invalid dniPropietario supplied
        '404':
          description: Vehicle not found
    post:
      tags:
        - vehicle
      summary: crea un nuevo vehiculo
      description: vehicles
      operationId: createVehicle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '405':
          description: Invalid input


  /polizyes/{idPoliza}/parts:
    post:
      tags:
        - policy
      parameters:
        - name: idPoliza
          in: path
          description: idPoliza of part that needs to be fetched
          required: true
          schema:
            type: string
      summary: Place a part for a policy
      description: Place a new part in the policy?
      operationId: savePart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Part'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '405':
          description: Invalid input

  /users/{benefitDni}/parts:
    get:
      tags:
        - part
      summary: Get parts by benefitDni
      description: ''
      operationId: getPartsByDni
      parameters:
        - name: benefitDni
          in: path
          description: '¿?-¿?'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: Invalid benefitDni supplied
        '404':
          description: part not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dni:
          type: string
        name:
          type: string
        surName:
          type: string
        address:
          type: string
        iban:
          type: string
        email:
          type: string
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        birthday:
          type: string
          format: Date <'Y-m-d'>
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      required:
        - dni
        - name
        - surname
        - iban
        - email
        - birthday
        - address
        - password
        - phone
    Policy:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        userDni:
          type: string
        benefitDni:
          type: string
        type:
          type: string
          description: policy type
          enum:
            - fullrisk
            - thirds
        vehicle:
          type: string

    PolicyTypes:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Vehicle:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        dniPropietario:
          type: string
          description: dni propietario del vehiculo != al dni tomadorseguro
        marca:
          type: string
          description: hyundai , bmw , ferrari...
        modelo:
          type: string
          description: modelo del coche
        fechaMatriculacion:
          type: string
          format: date
        matricula:
          type: string
      required:
        - marca
        - modelo
        - fechaMatriculacion
        - matricula

    Part:
      type: object
      properties:
        id:
          type: integer
          format: int64
        benefitDni:
          type: string
        affectedDni:
          type: string
        policyId:
          type: integer
          format: int64
        addInfo:
          type: string
        pay:
          type: boolean
      required:
        - benefitDni
        - affectedDni
        - policyId

    Peritage:
      type: object
      properties:
        idPart:
          type: integer
        idDecission:
          type: integer
        information:
          type: string
      required:
        - idPart
        - idDecission

    Decission:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
